#!/bin/sh
ip rule add from $ifconfig_local table brandenburg priority 9970
ip route add 0.0.0.0/1 via $route_vpn_gateway dev $dev table brandenburg
ip route add 128.0.0.0/1 via $route_vpn_gateway dev $dev table brandenburg
# NAT aktivieren, wird benötigt wenn NICHT Berlin
#iptables -t nat -A POSTROUTING -o $dev -j MASQUERADE
exit 0
